export const FETCH_SHIPMENTS_REQUEST = 'FETCH_SHIPMENTS_REQUEST';
export const FETCH_SHIPMENTS_SUCCESS = 'FETCH_SHIPMENTS_SUCCESS';
export const FETCH_SHIPMENTS_FAILURE = 'FETCH_SHIPMENTS_FAILURE';
export const DELETE_SHIPMENT = 'DELETE_SHIPMENT';
